github: [devinschumacher]

liberapay: devinschumacher

open_collective: devinschumacher

custom: [
"https://devinschumacher.com",
"https://serp.co",
"https://serp.ai",
"https://boxingundefeated.com"
]
