// URL to content file mappings
export const urlMappings: Record<string, string> = {
  // Blog posts from blog.devinschumacher.com
  '/download-any-vimeo-video-easily-on-public-or-private-web-pages-w-vimeo-video-downloader-v200/': 'blog/download-vimeo-video',
  '/how-to-combine-merge-multiple-csv-or-excel-files-for-mac-pc-and-linux/': 'blog/combine-csv-excel-files',
  '/how-to-download-skoolcom-videos-wget/': 'blog/download-skool-videos',
  '/how-to-download-vimeo-videos/': 'blog/download-vimeo-videos',
  '/how-to-hide-archived-repositories-from-github-search-f888177e9090/': 'blog/hide-github-archived-repos',
  '/how-to-reopen-restore-closed-tabs-in-any-browser-chrome-safari-firefox-no-extension-or-tools/': 'blog/restore-closed-tabs',
  '/how-to-use-chrome-developer-mode-to-use-unofficial-browser-extensions-865c35b58800/': 'blog/chrome-developer-mode',

  // How-to-download posts
  '/how-to-download-skool-videos-m3u8-token/': 'how-to-download/how-to-download-skool-videos-m3u8-token',
  '/how-to-download-long-vimeo-videos-dash-streams-with-yt-dlp/': 'how-to-download/how-to-download-long-vimeo-videos-dash-streams-with-yt-dlp',
  '/how-to-download-password-protected-vimeo-videos-with-yt-dlp/': 'how-to-download/how-to-download-password-protected-vimeo-videos-with-yt-dlp',
  '/how-to-download-circle-so-videos-free/': 'how-to-download/how-to-download-circle-so-videos-free',
  '/how-to-download-coursera-videos/': 'how-to-download/how-to-download-coursera-videos',
  '/how-to-download-hls-m3u8-streaming-videos/': 'how-to-download/how-to-download-hls-m3u8-streaming-videos',
  '/how-to-download-loom-videos/': 'how-to-download/how-to-download-loom-videos',
  '/how-to-download-onlyfans-profiles-videos-images/': 'how-to-download/how-to-download-onlyfans-profiles-videos-images',
  '/how-to-download-password-protected-vimeo-videos/': 'how-to-download/how-to-download-password-protected-vimeo-videos',
  '/how-to-download-skool-videos-and-entire-course/': 'how-to-download/how-to-download-skool-videos-and-entire-course',
  '/how-to-download-skool-videos-with-signed-m3u8/': 'how-to-download/how-to-download-skool-videos-with-signed-m3u8',
  '/how-to-download-skool-videos-with-yt-dlp/': 'how-to-download/how-to-download-skool-videos-with-yt-dlp',
  '/how-to-download-tiktok-audio-music-audio-etc-from-videos/': 'how-to-download/how-to-download-tiktok-audio-music-audio-etc-from-videos',
  '/how-to-download-tiktok-videos/': 'how-to-download/how-to-download-tiktok-videos',
  '/how-to-download-udemy-videos/': 'how-to-download/how-to-download-udemy-videos',
  '/how-to-download-vimeo-videos-method-2-yt-dlp-at-the-m3u8-stream/': 'how-to-download/how-to-download-vimeo-videos-method-2-yt-dlp-at-the-m3u8-stream',
  '/how-to-download-vimeo-videos-streaming-via-hls-streamlink/': 'how-to-download/how-to-download-vimeo-videos-streaming-via-hls-streamlink',
  '/how-to-download-webrtc-video-streams/': 'how-to-download/how-to-download-webrtc-video-streams',
  '/how-to-download-whop-videos/': 'how-to-download/how-to-download-whop-videos',
  '/how-to-download-wistia-videos-using-network-requests/': 'how-to-download/how-to-download-wistia-videos-using-network-requests',
  '/how-to-download-youtube-videos-for-free-with-yt-dlp/': 'how-to-download/how-to-download-youtube-videos-for-free-with-yt-dlp',
  
  // SEO content - these should map to existing files in content/blog/seo/
  '/anchor-text/': 'seo/anchor-text',
  '/black-hat-seo/': 'seo/black-hat-seo',
  '/citations/': 'seo/citations',
  '/do-follow-links/': 'seo/do-follow-links',
  '/google-dance/': 'seo/google-dance',
  '/google-maps-marketing-strategies/': 'seo/google-maps-marketing-strategies',
  '/google-ranking-factors/': 'seo/google-ranking-factors',
  '/image-filenames/': 'seo/image-filenames',
  '/keyword-density/': 'seo/keyword-density',
  '/keyword-difficulty/': 'seo/keyword-difficulty',
  '/link-building/': 'seo/link-building',
  '/local-seo/': 'seo/local-seo',
  '/lsi-keywords/': 'seo/lsi-keywords',
  '/meta-keywords/': 'seo/meta-keywords',
  '/no-follow-links/': 'seo/no-follow-links',
  '/on-page-seo/': 'seo/on-page-seo',
  '/off-page-seo/': 'seo/off-page-seo',
  '/robots-txt/': 'seo/robots-txt',
  '/search-engines/': 'seo/search-engines',
  '/search-intent/': 'seo/search-intent',
  '/search-query/': 'seo/search-query',
  '/search-volume/': 'seo/search-volume',
  '/seed-keywords/': 'seo/seed-keywords',
  '/seo/': 'seo/seo',
  '/seo-keywords/': 'seo/seo-keywords',
  '/seo-tags/': 'seo/seo-tags',
  '/seo-techniques/': 'seo/seo-techniques',
  '/serp/': 'seo/serp',
  '/serp-features/': 'seo/serp-features',
  '/sitemaps/': 'seo/sitemaps',
  '/title-tags/': 'seo/title-tags',
  '/url-structure/': 'seo/url-structure',
  '/web-crawlers/': 'seo/web-crawlers',
  '/what-is-seo/': 'seo/what-is-seo',
  '/white-hat-seo/': 'seo/white-hat-seo',
  '/duplicate-content/': 'seo/duplicate-content',
  '/internal-links/': 'seo/internal-links',
  '/alt-text/': 'seo/alt-text',
  
  // Python posts
  '/python-float/': 'python/python-float',
  '/python-get-method-requests-get/': 'python/python-get-method-requests-get',
  '/python-lists/': 'python/python-lists',
  '/python-print-table/': 'python/python-print-table',
  '/python-requests-library/': 'python/python-requests-library',
  '/how-to-read-csv-w-the-python-csv-module-csv-reader-csv-dictreader/': 'python/how-to-read-csv-w-the-python-csv-module-csv-reader-csv-dictreader',
  '/how-to-combine-merge-multiple-csv-or-excel-files-for-mac-pc/': 'python/how-to-combine-merge-multiple-csv-or-excel-files-for-mac-pc',
  '/how-to-setup-jupyter-notebook-virtual-environment-vs-code-kernels/': 'python/how-to-setup-jupyter-notebook-virtual-environment-vs-code-kernels',
  '/chinchilla-ai/': 'python/chinchilla-ai',
  
  // Git posts
  '/git-fetch/': 'git/git-fetch',
  '/git/': 'git/git',
  
  // JavaScript posts
  '/array-destructuring/': 'javascript/array-destructuring',
  '/javascript-callbacks/': 'javascript/javascript-callbacks',
  '/javascript-rest-operator-spread-operator/': 'javascript/javascript-rest-operator-spread-operator',
  '/rendering-modes-ssr-spa-ur-etc/': 'javascript/rendering-modes-ssr-spa-ur-etc',
  '/notes-understanding-typescript-course/': 'javascript/notes-understanding-typescript-course',
  
  // TypeScript posts
  '/arrays-in-typescript/': 'typescript/arrays-in-typescript',
  '/typing-component-events-in-vue/': 'typescript/typing-component-events-in-vue',
  '/cloudflare-301-redirects-url-forwarding/': 'typescript/cloudflare-301-redirects-url-forwarding',
  '/typescript-any-type/': 'typescript/typescript-any-type',
  '/typescript-enum-types/': 'typescript/typescript-enum-types',
  '/typescript-function-returns/': 'typescript/typescript-function-returns',
  '/typescript-function-types/': 'typescript/typescript-function-types',
  '/typescript-type-alisas-aka-custom-types/': 'typescript/typescript-type-alisas-aka-custom-types',
  '/typescript-union-types/': 'typescript/typescript-union-types',
  
  // Vue posts
  '/navigation-guards/': 'vue/navigation-guards',
  '/computed-properties-computed-in-vue-nuxt/': 'vue/computed-properties-computed-in-vue-nuxt',
  
  // AI posts
  '/audio-diffusion-ai/': 'ai/audio-diffusion-ai',
  '/tailwind-directives/': 'ai/tailwind-directives',
  '/tailwind-functions/': 'ai/tailwind-functions',
  
  // Marketing posts
  '/email-marketing-tips/': 'marketing/email-marketing-tips',
  '/how-dental-marketing-is-changing-marketing/': 'marketing/how-dental-marketing-is-changing-marketing',
  
  // Tech posts
  '/snapshot-testing-with-vitest/': 'tech/snapshot-testing-with-vitest',
  '/ctr-manipulation-tools/': 'tech/ctr-manipulation-tools',
  '/grow-your-linkedin-profile-faster-w-auto-follow-links/': 'tech/grow-your-linkedin-profile-faster-w-auto-follow-links',
  '/how-to-completely-delete-applications-on-mac-full-uninstallation/': 'tech/how-to-completely-delete-applications-on-mac-full-uninstallation',
  '/how-to-disable-prettier-formatting-for-individual-files-or-folders/': 'tech/how-to-disable-prettier-formatting-for-individual-files-or-folders',
  '/how-to-setup-g-suite-mx-records-google-workspace-spf-dkim-dmarc/': 'tech/how-to-setup-g-suite-mx-records-google-workspace-spf-dkim-dmarc',
  '/sql-show/': 'tech/sql-show',
  '/http-vs-https/': 'seo/http-vs-https',
  '/hyperlinks/': 'seo/hyperlinks',
  '/long-tail-keywords/': 'seo/long-tail-keywords',
  '/keyword-research/': 'seo/keyword-research',
  '/checklist/': 'seo/checklist',
  '/backlinks/': 'seo/backlinks',
  
  // Best/Review content
  '/best/2-room-camping-tents/': 'best/2-room-camping-tents',
  '/best/ai-agents/': 'best/ai-agents',
  '/best/ai-chatbots/': 'best/ai-chatbots',
  '/best/ai-image-generator/': 'best/ai-image-generator',
  '/best/ai-investing-software/': 'best/ai-investing-software',
  '/best/ai-novel-writing-software/': 'best/ai-novel-writing-software',
  '/best/ai-writing-software/': 'best/ai-writing-software',
  '/best/animation-software/': 'best/animation-software',
  '/best/asset-management-software/': 'best/asset-management-software',
  '/best/audio-editing-software/': 'best/audio-editing-software',
  '/best/auto-dialer-software/': 'best/auto-dialer-software',
  '/best/business-intelligence-tools/': 'best/business-intelligence-tools',
  '/best/cad-software/': 'best/cad-software',
  '/best/cheap-cloud-gpus/': 'best/cheap-cloud-gpus',
  '/best/cheap-dedicated-hosting-providers/': 'best/cheap-dedicated-hosting-providers',
  '/best/cloud-gpu-providers/': 'best/cloud-gpu-providers',
  '/best/cloud-storage-services/': 'best/cloud-storage-services',
  '/best/crm-software/': 'best/crm-software',
  '/best/ctr-manipulation-tools/': 'best/ctr-manipulation-tools',
  '/best/data-migration-software/': 'best/data-migration-software',
  '/best/data-visualization-tools/': 'best/data-visualization-tools',
  '/best/database-software/': 'best/database-software',
  '/best/email-marketing-software/': 'best/email-marketing-software',
  '/best/grammar-checking-tools/': 'best/grammar-checking-tools',
  '/best/graphic-design-software/': 'best/graphic-design-software',
  '/best/green-screen-software/': 'best/green-screen-software',
  '/best/inventory-management-software/': 'best/inventory-management-software',
  '/best/invoicing-software/': 'best/invoicing-software',
  '/best/keyword-rank-tracking-tools/': 'best/keyword-rank-tracking-tools',
  '/best/lead-generation-tools/': 'best/lead-generation-tools',
  '/best/learning-management-systems/': 'best/learning-management-systems',
  '/best/local-seo-software/': 'best/local-seo-software',
  '/best/market-research-tools/': 'best/market-research-tools',
  '/best/marketing-automation-software/': 'best/marketing-automation-software',
  '/best/membership-site-platforms/': 'best/membership-site-platforms',
  '/best/money-making-apps/': 'best/money-making-apps',
  '/best/ocr-software/': 'best/ocr-software',
  '/best/online-graphic-design-tools/': 'best/online-graphic-design-tools',
  '/best/online-learning-platforms/': 'best/online-learning-platforms',
  '/best/photo-editing-software/': 'best/photo-editing-software',
  '/best/photo-management-software/': 'best/photo-management-software',
  '/best/podcast-editing-software/': 'best/podcast-editing-software',
  '/best/podcast-recording-software/': 'best/podcast-recording-software',
  '/best/proxy-server/': 'best/proxy-server',
  '/best/review-management-software/': 'best/review-management-software',
  '/best/scheduling-software/': 'best/scheduling-software',
  '/best/screenwriting-software-free/': 'best/screenwriting-software-free',
  '/best/scrum-tools/': 'best/scrum-tools',
  '/best/seo-tools/': 'best/seo-tools',
  '/best/streaming-software/': 'best/streaming-software',
  '/best/survey-software/': 'best/survey-software',
  '/best/transcription-software/': 'best/transcription-software',
  '/best/video-editing-software/': 'best/video-editing-software',
  '/best/video-platforms/': 'best/video-platforms',
  '/best/vpn-services/': 'best/vpn-services',
  '/best/web-design-software/': 'best/web-design-software',
  '/best/web-scraping-tools/': 'best/web-scraping-tools',
  '/best/webinar-software/': 'best/webinar-software',
  
  // Comparison content
  '/comparison/bigcommerce-vs-shopify/': 'comparison/bigcommerce-vs-shopify',
  '/comparison/canva-vs-picmonkey/': 'comparison/canva-vs-picmonkey',
  '/comparison/crello-vs-canva/': 'comparison/crello-vs-canva',
  '/comparison/kajabi-vs-teachable/': 'comparison/kajabi-vs-teachable',
  '/comparison/streamlabs-vs-obs/': 'comparison/streamlabs-vs-obs',
  '/comparison/webex-vs-zoom/': 'comparison/webex-vs-zoom',
  '/comparison/wix-vs-wordpress/': 'comparison/wix-vs-wordpress',
  
  // Reviews
  '/reviews/a-small-orange/': 'reviews/a-small-orange',
  '/reviews/a2-hosting/': 'reviews/a2-hosting',
  '/reviews/acenet-hosting/': 'reviews/acenet-hosting',
  '/reviews/apex-hosting/': 'reviews/apex-hosting',
  '/reviews/arvixe-hosting/': 'reviews/arvixe-hosting',
  '/reviews/bandzoogle-hosting/': 'reviews/bandzoogle-hosting',
  '/reviews/bisecthosting/': 'reviews/bisecthosting',
  '/reviews/blinklist/': 'reviews/blinklist',
  '/reviews/clickfunnels/': 'reviews/clickfunnels',
  '/reviews/cloudways/': 'reviews/cloudways',
  '/reviews/codero-hosting/': 'reviews/codero-hosting',
  '/reviews/convertkit/': 'reviews/convertkit',
  '/reviews/crello/': 'reviews/crello',
  '/reviews/demio/': 'reviews/demio',
  '/reviews/digitalocean/': 'reviews/digitalocean',
  '/reviews/directnic/': 'reviews/directnic',
  '/reviews/dot5hosting/': 'reviews/dot5hosting',
  '/reviews/dotster/': 'reviews/dotster',
  '/reviews/dreamhost/': 'reviews/dreamhost',
  '/reviews/enom/': 'reviews/enom',
  '/reviews/ever-webinar/': 'reviews/ever-webinar',
  '/reviews/fastcomet/': 'reviews/fastcomet',
  '/reviews/fatcow/': 'reviews/fatcow',
  '/reviews/flywheel/': 'reviews/flywheel',
  '/reviews/freehostia/': 'reviews/freehostia',
  '/reviews/glockapps/': 'reviews/glockapps',
  '/reviews/godaddy/': 'reviews/godaddy',
  '/reviews/greengeeks/': 'reviews/greengeeks',
  '/reviews/hetzner/': 'reviews/hetzner',
  '/reviews/hivelocity/': 'reviews/hivelocity',
  '/reviews/hostek/': 'reviews/hostek',
  '/reviews/hostgator/': 'reviews/hostgator',
  '/reviews/hosting24/': 'reviews/hosting24',
  '/reviews/hostpapa/': 'reviews/hostpapa',
  '/reviews/hostway/': 'reviews/hostway',
  '/reviews/hostwinds/': 'reviews/hostwinds',
  '/reviews/inmotion-hosting/': 'reviews/inmotion-hosting',
  '/reviews/internap/': 'reviews/internap',
  '/reviews/ionos/': 'reviews/ionos',
  '/reviews/ipage/': 'reviews/ipage',
  '/reviews/ipower/': 'reviews/ipower',
  '/reviews/justhost/': 'reviews/justhost',
  '/reviews/kajabi/': 'reviews/kajabi',
  '/reviews/kamatera/': 'reviews/kamatera',
  '/reviews/kinghost/': 'reviews/kinghost',
  '/reviews/leadific/': 'reviews/leadific',
  '/reviews/leadpages/': 'reviews/leadpages',
  '/reviews/learnworlds/': 'reviews/learnworlds',
  '/reviews/leaseweb/': 'reviews/leaseweb',
  '/reviews/linode/': 'reviews/linode',
  '/reviews/mailchimp/': 'reviews/mailchimp',
  '/reviews/mailshake/': 'reviews/mailshake',
  '/reviews/manychat/': 'reviews/manychat',
  '/reviews/meloncube/': 'reviews/meloncube',
  '/reviews/minitool-software/': 'reviews/minitool-software',
  '/reviews/namecheap-hosting/': 'reviews/namecheap-hosting',
  '/reviews/network-solutions/': 'reviews/network-solutions',
  '/reviews/nexcess/': 'reviews/nexcess',
  '/reviews/one-com/': 'reviews/one-com',
  '/reviews/originality-ai/': 'reviews/originality-ai',
  '/reviews/ovhcloud/': 'reviews/ovhcloud',
  '/reviews/pebblehost/': 'reviews/pebblehost',
  '/reviews/penji/': 'reviews/penji',
  '/reviews/picmonkey/': 'reviews/picmonkey',
  '/reviews/podia/': 'reviews/podia',
  '/reviews/powweb/': 'reviews/powweb',
  '/reviews/pressable/': 'reviews/pressable',
  '/reviews/readyhosting/': 'reviews/readyhosting',
  '/reviews/site5/': 'reviews/site5',
  '/reviews/siteground/': 'reviews/siteground',
  '/reviews/snappa/': 'reviews/snappa',
  '/reviews/startlogic/': 'reviews/startlogic',
  '/reviews/teachable/': 'reviews/teachable',
  '/reviews/teachery/': 'reviews/teachery',
  '/reviews/thinkific/': 'reviews/thinkific',
  '/reviews/tmdhosting/': 'reviews/tmdhosting',
  '/reviews/tucows/': 'reviews/tucows',
  '/reviews/unbounce/': 'reviews/unbounce',
  '/reviews/quillbot/': 'reviews/quillbot',
  '/reviews/vidiq/': 'reviews/vidiq',
  '/reviews/webinarjam/': 'reviews/webinarjam',
  '/reviews/wp-engine/': 'reviews/wp-engine',
  '/reviews/writesonic/': 'reviews/writesonic',
  '/reviews/yahoo-web-hosting/': 'reviews/yahoo-web-hosting',
  '/reviews/zap-hosting/': 'reviews/zap-hosting',
  '/reviews/zapier/': 'reviews/zapier',
  
  // Technical/Tutorial content (not migrated yet)
  '/attorney-business-cards/': 'guides/attorney-business-cards',
  '/dental-marketing-ideas/': 'guides/dental-marketing-ideas',
  '/digital-marketing-certifications/': 'guides/digital-marketing-certifications',
  '/digital-marketing-for-dummies/': 'guides/digital-marketing-for-dummies',
  '/how-to-promote-your-blog/': 'guides/promote-your-blog',
  '/law-firm-branding/': 'guides/law-firm-branding',
  '/law-firm-logos/': 'guides/law-firm-logos',
  '/social-media-management-tools/': 'guides/social-media-management-tools',
  '/what-is-content-marketing/': 'guides/what-is-content-marketing',
  '/what-is-lead-generation/': 'guides/what-is-lead-generation',
};

// Get all available URL paths
export function getAllUrlPaths(): string[] {
  return Object.keys(urlMappings);
}

// Get content path for a given URL
export function getContentPath(url: string): string | undefined {
  // Normalize URL to ensure it has trailing slash
  const normalizedUrl = url.endsWith('/') ? url : `${url}/`;
  return urlMappings[normalizedUrl];
}

// Check if a URL is mapped
export function isUrlMapped(url: string): boolean {
  const normalizedUrl = url.endsWith('/') ? url : `${url}/`;
  return normalizedUrl in urlMappings;
}
