// URL to content file mappings
export const urlMappings: Record<string, string> = {
  // Blog posts from blog.devinschumacher.com
  '/download-any-vimeo-video-easily-on-public-or-private-web-pages-w-vimeo-video-downloader-v200/': 'blog/download-vimeo-video',
  '/how-to-combine-merge-multiple-csv-or-excel-files-for-mac-pc-and-linux/': 'blog/combine-csv-excel-files',
  '/how-to-download-skoolcom-videos-wget/': 'blog/download-skool-videos',
  '/how-to-download-vimeo-videos/': 'blog/download-vimeo-videos',
  '/how-to-hide-archived-repositories-from-github-search-f888177e9090/': 'blog/hide-github-archived-repos',
  '/how-to-reopen-restore-closed-tabs-in-any-browser-chrome-safari-firefox-no-extension-or-tools/': 'blog/restore-closed-tabs',
  '/how-to-use-chrome-developer-mode-to-use-unofficial-browser-extensions-865c35b58800/': 'blog/chrome-developer-mode',
  
  // SEO content - these should map to existing files in content/blog/seo/
  '/anchor-text/': 'seo/anchor-text',
  '/black-hat-seo/': 'seo/black-hat-seo',
  '/citations/': 'seo/citations',
  '/do-follow-links/': 'seo/do-follow-links',
  '/google-dance/': 'seo/google-dance',
  '/google-maps-marketing-strategies/': 'seo/google-maps-marketing-strategies',
  '/google-ranking-factors/': 'seo/google-ranking-factors',
  '/image-filenames/': 'seo/image-filenames',
  '/keyword-density/': 'seo/keyword-density',
  '/keyword-difficulty/': 'seo/keyword-difficulty',
  '/link-building/': 'seo/link-building',
  '/local-seo/': 'seo/local-seo',
  '/lsi-keywords/': 'seo/lsi-keywords',
  '/meta-keywords/': 'seo/meta-keywords',
  '/no-follow-links/': 'seo/no-follow-links',
  '/on-page-seo/': 'seo/on-page-seo',
  '/off-page-seo/': 'seo/off-page-seo',
  '/robots-txt/': 'seo/robots-txt',
  '/search-engines/': 'seo/search-engines',
  '/search-intent/': 'seo/search-intent',
  '/search-query/': 'seo/search-query',
  '/search-volume/': 'seo/search-volume',
  '/seed-keywords/': 'seo/seed-keywords',
  '/seo/': 'seo/seo',
  '/seo-keywords/': 'seo/seo-keywords',
  '/seo-tags/': 'seo/seo-tags',
  '/seo-techniques/': 'seo/seo-techniques',
  '/serp/': 'seo/serp',
  '/serp-features/': 'seo/serp-features',
  '/sitemaps/': 'seo/sitemaps',
  '/title-tags/': 'seo/title-tags',
  '/url-structure/': 'seo/url-structure',
  '/web-crawlers/': 'seo/web-crawlers',
  '/what-is-seo/': 'seo/what-is-seo',
  '/white-hat-seo/': 'seo/white-hat-seo',
  '/duplicate-content/': 'seo/duplicate-content',
  '/internal-links/': 'seo/internal-links',
  '/alt-text/': 'seo/alt-text',
  '/hyperlinks/': 'seo/hyperlinks',
  '/long-tail-keywords/': 'seo/long-tail-keywords',
  '/keyword-research/': 'seo/keyword-research',
  '/checklist/': 'seo/checklist',
  '/backlinks/': 'seo/backlinks',
  
  // Best/Review content
  '/best/2-room-camping-tents/': 'best/2-room-camping-tents',
  '/best/ai-chatbots/': 'best/ai-chatbots',
  '/best/ai-investing-software/': 'best/ai-investing-software',
  '/best/ai-novel-writing-software/': 'best/ai-novel-writing-software',
  '/best/ai-writing-software/': 'best/ai-writing-software',
  '/best/audio-editing-software/': 'best/audio-editing-software',
  '/best/auto-dialer-software/': 'best/auto-dialer-software',
  '/best/business-intelligence-tools/': 'best/business-intelligence-tools',
  '/best/cad-software/': 'best/cad-software',
  '/best/cheap-cloud-gpus/': 'best/cheap-cloud-gpus',
  '/best/cheap-dedicated-hosting-providers/': 'best/cheap-dedicated-hosting-providers',
  '/best/cloud-gpu-providers/': 'best/cloud-gpu-providers',
  '/best/cloud-storage-services/': 'best/cloud-storage-services',
  '/best/ctr-manipulation-tools/': 'best/ctr-manipulation-tools',
  '/best/data-migration-software/': 'best/data-migration-software',
  '/best/database-software/': 'best/database-software',
  '/best/grammar-checking-tools/': 'best/grammar-checking-tools',
  '/best/graphic-design-software/': 'best/graphic-design-software',
  '/best/green-screen-software/': 'best/green-screen-software',
  '/best/inventory-management-software/': 'best/inventory-management-software',
  '/best/invoicing-software/': 'best/invoicing-software',
  '/best/keyword-rank-tracking-tools/': 'best/keyword-rank-tracking-tools',
  '/best/local-seo-software/': 'best/local-seo-software',
  '/best/market-research-tools/': 'best/market-research-tools',
  '/best/marketing-automation-software/': 'best/marketing-automation-software',
  '/best/membership-site-platforms/': 'best/membership-site-platforms',
  '/best/money-making-apps/': 'best/money-making-apps',
  '/best/ocr-software/': 'best/ocr-software',
  '/best/online-learning-platforms/': 'best/online-learning-platforms',
  '/best/photo-editing-software/': 'best/photo-editing-software',
  '/best/photo-management-software/': 'best/photo-management-software',
  '/best/podcast-editing-software/': 'best/podcast-editing-software',
  '/best/podcast-recording-software/': 'best/podcast-recording-software',
  '/best/proxy-server/': 'best/proxy-server',
  '/best/scheduling-software/': 'best/scheduling-software',
  '/best/screenwriting-software-free/': 'best/screenwriting-software-free',
  '/best/scrum-tools/': 'best/scrum-tools',
  '/best/streaming-software/': 'best/streaming-software',
  '/best/survey-software/': 'best/survey-software',
  '/best/transcription-software/': 'best/transcription-software',
  '/best/vpn-services/': 'best/vpn-services',
  '/best/web-design-software/': 'best/web-design-software',
  '/best/web-scraping-tools/': 'best/web-scraping-tools',
  '/best/webinar-software/': 'best/webinar-software',
  
  // Comparison content
  '/comparison/bigcommerce-vs-shopify/': 'comparison/bigcommerce-vs-shopify',
  '/comparison/canva-vs-picmonkey/': 'comparison/canva-vs-picmonkey',
  '/comparison/crello-vs-canva/': 'comparison/crello-vs-canva',
  '/comparison/kajabi-vs-teachable/': 'comparison/kajabi-vs-teachable',
  '/comparison/streamlabs-vs-obs/': 'comparison/streamlabs-vs-obs',
  '/comparison/webex-vs-zoom/': 'comparison/webex-vs-zoom',
  '/comparison/wix-vs-wordpress/': 'comparison/wix-vs-wordpress',
  
  // Reviews
  '/reviews/a-small-orange/': 'reviews/a-small-orange',
  '/reviews/acenet-hosting/': 'reviews/acenet-hosting',
  '/reviews/apex-hosting/': 'reviews/apex-hosting',
  '/reviews/bandzoogle-hosting/': 'reviews/bandzoogle-hosting',
  '/reviews/bisecthosting/': 'reviews/bisecthosting',
  '/reviews/blinklist/': 'reviews/blinklist',
  '/reviews/clickfunnels/': 'reviews/clickfunnels',
  '/reviews/cloudways/': 'reviews/cloudways',
  '/reviews/codero-hosting/': 'reviews/codero-hosting',
  '/reviews/convertkit/': 'reviews/convertkit',
  '/reviews/crello/': 'reviews/crello',
  '/reviews/demio/': 'reviews/demio',
  '/reviews/digitalocean/': 'reviews/digitalocean',
  '/reviews/directnic/': 'reviews/directnic',
  '/reviews/dot5hosting/': 'reviews/dot5hosting',
  '/reviews/dotster/': 'reviews/dotster',
  '/reviews/dreamhost/': 'reviews/dreamhost',
  '/reviews/enom/': 'reviews/enom',
  '/reviews/ever-webinar/': 'reviews/ever-webinar',
  '/reviews/fastcomet/': 'reviews/fastcomet',
  '/reviews/fatcow/': 'reviews/fatcow',
  '/reviews/flywheel/': 'reviews/flywheel',
  '/reviews/freehostia/': 'reviews/freehostia',
  '/reviews/glockapps/': 'reviews/glockapps',
  '/reviews/godaddy/': 'reviews/godaddy',
  '/reviews/greengeeks/': 'reviews/greengeeks',
  '/reviews/hetzner/': 'reviews/hetzner',
  '/reviews/hivelocity/': 'reviews/hivelocity',
  '/reviews/hostek/': 'reviews/hostek',
  '/reviews/hostgator/': 'reviews/hostgator',
  '/reviews/hosting24/': 'reviews/hosting24',
  '/reviews/hostpapa/': 'reviews/hostpapa',
  '/reviews/hostway/': 'reviews/hostway',
  '/reviews/hostwinds/': 'reviews/hostwinds',
  '/reviews/inmotion-hosting/': 'reviews/inmotion-hosting',
  '/reviews/internap/': 'reviews/internap',
  '/reviews/ionos/': 'reviews/ionos',
  '/reviews/ipage/': 'reviews/ipage',
  '/reviews/ipower/': 'reviews/ipower',
  '/reviews/justhost/': 'reviews/justhost',
  '/reviews/kajabi/': 'reviews/kajabi',
  '/reviews/kamatera/': 'reviews/kamatera',
  '/reviews/kinghost/': 'reviews/kinghost',
  '/reviews/leadific/': 'reviews/leadific',
  '/reviews/leadpages/': 'reviews/leadpages',
  '/reviews/learnworlds/': 'reviews/learnworlds',
  '/reviews/leaseweb/': 'reviews/leaseweb',
  '/reviews/linode/': 'reviews/linode',
  '/reviews/mailchimp/': 'reviews/mailchimp',
  '/reviews/mailshake/': 'reviews/mailshake',
  '/reviews/manychat/': 'reviews/manychat',
  '/reviews/meloncube/': 'reviews/meloncube',
  '/reviews/minitool-software/': 'reviews/minitool-software',
  '/reviews/namecheap-hosting/': 'reviews/namecheap-hosting',
  '/reviews/network-solutions/': 'reviews/network-solutions',
  '/reviews/nexcess/': 'reviews/nexcess',
  '/reviews/one-com/': 'reviews/one-com',
  '/reviews/originality-ai/': 'reviews/originality-ai',
  '/reviews/ovhcloud/': 'reviews/ovhcloud',
  '/reviews/pebblehost/': 'reviews/pebblehost',
  '/reviews/penji/': 'reviews/penji',
  '/reviews/picmonkey/': 'reviews/picmonkey',
  '/reviews/podia/': 'reviews/podia',
  '/reviews/powweb/': 'reviews/powweb',
  '/reviews/pressable/': 'reviews/pressable',
  '/reviews/readyhosting/': 'reviews/readyhosting',
  '/reviews/site5/': 'reviews/site5',
  '/reviews/siteground/': 'reviews/siteground',
  '/reviews/snappa/': 'reviews/snappa',
  '/reviews/startlogic/': 'reviews/startlogic',
  '/reviews/teachable/': 'reviews/teachable',
  '/reviews/teachery/': 'reviews/teachery',
  '/reviews/thinkific/': 'reviews/thinkific',
  '/reviews/tmdhosting/': 'reviews/tmdhosting',
  '/reviews/tucows/': 'reviews/tucows',
  '/reviews/unbounce/': 'reviews/unbounce',
  '/reviews/vidiq/': 'reviews/vidiq',
  '/reviews/webinarjam/': 'reviews/webinarjam',
  '/reviews/wp-engine/': 'reviews/wp-engine',
  '/reviews/yahoo-web-hosting/': 'reviews/yahoo-web-hosting',
  '/reviews/zap-hosting/': 'reviews/zap-hosting',
  '/reviews/zapier/': 'reviews/zapier',
  
  // Technical/Tutorial content
  '/attorney-business-cards/': 'guides/attorney-business-cards',
  '/audio-diffusion-ai/': 'guides/audio-diffusion-ai',
  '/chinchilla-ai/': 'guides/chinchilla-ai',
  '/cloudflare-301-redirects-url-forwarding/': 'guides/cloudflare-301-redirects',
  '/dental-marketing-ideas/': 'guides/dental-marketing-ideas',
  '/digital-marketing-certifications/': 'guides/digital-marketing-certifications',
  '/digital-marketing-for-dummies/': 'guides/digital-marketing-for-dummies',
  '/git-fetch/': 'guides/git-fetch',
  '/how-to-combine-merge-multiple-csv-or-excel-files-for-mac-pc/': 'guides/combine-csv-excel',
  '/how-to-completely-delete-applications-on-mac-full-uninstallation/': 'guides/delete-mac-apps',
  '/how-to-disable-prettier-formatting-for-individual-files-or-folders/': 'guides/disable-prettier',
  '/how-to-promote-your-blog/': 'guides/promote-your-blog',
  '/how-to-read-csv-w-the-python-csv-module-csv-reader-csv-dictreader/': 'guides/python-csv-module',
  '/how-to-setup-g-suite-mx-records-google-workspace-spf-dkim-dmarc/': 'guides/google-workspace-mx-records',
  '/how-to-setup-jupyter-notebook-virtual-environment-vs-code-kernels/': 'guides/jupyter-notebook-setup',
  '/http-vs-https/': 'guides/http-vs-https',
  '/law-firm-branding/': 'guides/law-firm-branding',
  '/law-firm-logos/': 'guides/law-firm-logos',
  '/python-float/': 'guides/python-float',
  '/python-print-table/': 'guides/python-print-table',
  '/social-media-management-tools/': 'guides/social-media-management-tools',
  '/sql-show/': 'guides/sql-show',
  '/what-is-content-marketing/': 'guides/what-is-content-marketing',
  '/what-is-lead-generation/': 'guides/what-is-lead-generation',
};

// Get all available URL paths
export function getAllUrlPaths(): string[] {
  return Object.keys(urlMappings);
}

// Get content path for a given URL
export function getContentPath(url: string): string | undefined {
  // Normalize URL to ensure it has trailing slash
  const normalizedUrl = url.endsWith('/') ? url : `${url}/`;
  return urlMappings[normalizedUrl];
}

// Check if a URL is mapped
export function isUrlMapped(url: string): boolean {
  const normalizedUrl = url.endsWith('/') ? url : `${url}/`;
  return normalizedUrl in urlMappings;
}