name: Check Markdown Links
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly on Monday at 2 AM UTC
    - cron: '0 2 * * 1'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check links in markdown files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: 'content'
          config-file: '.markdown-link-check.json'
          check-modified-files-only: false
          base-branch: main